import { View, Text, TouchableOpacity, ScrollView, StyleSheet } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

const ROW_STYLE = { marginBottom: 16 };

export default function PrivacyScreen() {
  const router = useRouter();
  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()} testID="back-btn">
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Privacy &amp; AI Disclosure</Text>
      </View>
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.updated}>Last updated: 2026</Text>

        <Text style={styles.sectionTitle}>On-Device mode</Text>
        <Text style={styles.body} testID="privacy-ondevice">
          By default, Adaptive Tutor runs entirely on your device. Profiles, answers, mastery,
          streaks, and your API key stay in the app&apos;s local database and secure storage.
          In On-Device mode with a downloaded model, nothing you type or ask is sent over the network.
        </Text>

        <Text style={styles.sectionTitle}>Cloud mode (OpenRouter)</Text>
        <Text style={styles.body} testID="privacy-cloud">
          Cloud mode is optional and bring-your-own-key. When you switch the LLM Provider to
          OpenRouter, the questions you ask and your answers are sent to OpenRouter to generate
          tutoring responses and grades. OpenRouter passes content to the model provider you select.
          We do not sell your data or use it for advertising. You can turn Cloud mode off at any time
          in Settings — profiles and progress stay on your device.
        </Text>

        <Text style={styles.sectionTitle}>AI-generated content</Text>
        <Text style={styles.body} testID="privacy-ai">
          Tutoring responses, lessons, quizzes, and grades are generated by an AI model. Content may
          occasionally be inaccurate, incomplete, or unsuitable for your goals. Parental or guardian
          guidance is recommended for learners under 18. Always use your judgment and verify
          important information before acting on it. Adaptive Tutor is a study aid, not a substitute
          for professional medical, legal, or financial advice.
        </Text>

        <Text style={styles.sectionTitle}>Children (COPPA / GDPR-K)</Text>
        <Text style={styles.body}>
          Adaptive Tutor is designed for general audiences aged 13 and up. We do not knowingly
          collect personal information from children under 13. The app stores all data locally and
          never transmits it unless you explicitly enable Cloud mode with your own key.
        </Text>

        <Text style={styles.sectionTitle}>Your data &amp; deletion</Text>
        <Text style={styles.body}>
          Deleting a profile in the app removes its locally stored messages, progress, and settings.
          An API key stored for a profile is removed from the SecureStore when you delete the profile.
        </Text>

        <Text style={styles.sectionTitle}>Contact</Text>
        <Text style={styles.body}>
          Questions about privacy? Contact us at privacy@adaptivetutor.example.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    gap: 12,
  },
  backBtn: { padding: 4 },
  backText: { fontSize: 15, color: "#6366f1" },
  title: { fontSize: 17, fontWeight: "700", color: "#111", flex: 1 },
  container: { padding: 20, paddingBottom: 40 },
  updated: { fontSize: 12, color: "#9ca3af", marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: "600", color: "#111", marginBottom: 6, marginTop: 8 },
  body: { fontSize: 14, color: "#374151", lineHeight: 21, ...ROW_STYLE },
});